- hosts: all
  tasks: 
  - name: Copy file with owner and permissions
    copy:
      src: /tmp/kaizen.yml                       #local machine
      dest: /root/hello.yml                      #remote machine
      remote_src: yes 

  - name: Create user 
    shell: mkdir -p kaizen   